kind: Secret
apiVersion: v1
metadata:
  name: mistral-small-24b-instruct-2501-15
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: 'mistral-small-24b-instruct-2501:1.5'
    openshift.io/display-name: 'mistral-small-24b-instruct-2501:1.5'
data:
  URI: b2NpOi8vcmVnaXN0cnkucmVkaGF0LmlvL3JoZWxhaTEvbW9kZWxjYXItbWlzdHJhbC1zbWFsbC0yNGItaW5zdHJ1Y3QtMjUwMToxLjU=
type: Opaque
