kind: Secret
apiVersion: v1
metadata:
  name: qwen2-5-7b-instruct-fp8-dynamic-15
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-protocol: uri
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: 'qwen2-5-7b-instruct-fp8-dynamic:1.5'
    openshift.io/display-name: 'qwen2-5-7b-instruct-fp8-dynamic:1.5'
data:
  URI: b2NpOi8vcmVnaXN0cnkucmVkaGF0LmlvL3JoZWxhaTEvbW9kZWxjYXItcXdlbjItNS03Yi1pbnN0cnVjdC1mcDgtZHluYW1pYzoxLjU=
type: Opaque
